--!strict

return  {
	{duration = 0.05, text = "fsck exited with status code 8"},
	{duration = 0.1, text = "disconnected from: 5.100.98.75"},
	{duration = 0.05, text = "disconnected from: 5.100.98.121"},

	{duration = 0.05, text = "vm_page_bootstrap: 987323 free pages and 53061 wired pages"},
	{duration = 0.05, text = "kext submap [0xffffff7f8072e000 - 0xffffff8000000000], kernel text [0xffffff8000200000 - 0xffffff800072e000]"},
	{duration = 0.05, text = "shutting down qDOS modules"},
	{duration = 0.5, text = "attemping to detatch mount from filesystem readonly on device 179:2."}
}